language: java
sudo: false
install: true


jdk:
  - oraclejdk8

script:
  - ./gradlew test

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
